cc_test(
    name = "eth_layer_tests",
    srcs = glob(["*.cpp"]),
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//eth_layer:ancho_net_middleware_eth_layer"
        
    ],
)
