load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "commands",
    hdrs = ["commands.h"],
    visibility = ["//agent_server:__pkg__",
                  "//utils/tests:__pkg__",
                  "//utils:__pkg__",
                  "//message_handlers:__pkg__",
                  "//agents_middleware:__pkg__",
                 ]
            )
