load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "commons",
   
    hdrs = ["commons.h"],
    visibility = ["//agent_server:__pkg__",
                  "//utils/tests:__pkg__",
                  "//utils:__pkg__",
                  "//message_handlers:__pkg__",
                  "//agents_middleware:__pkg__",
                  "//devices_proxys:__pkg__",
                  "//eth_layer:__pkg__",
                  "//builder:__pkg__",
                  "//communication:__pkg__",
                  "//message_handlers:__pkg__",
                  "//message_handlers/tests:__pkg__",
                 ]
            )
