load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "ancho_net_middleware_server",
    srcs = [""],
    hdrs = ["agent_server.h"],
)

cc_binary(
    name = "ancho_router_server",
    srcs = ["main.cpp"],
)
