/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_AGENT_INTERFACE_MESSAGE_INTERFACE_IDL_PB_H_INCLUDED
#define PB_AGENT_INTERFACE_MESSAGE_INTERFACE_IDL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _agent_interface_CommandWithArguments_Arguments { 
    agent_interface_CommandWithArguments_Arguments_ONE = 0, 
    agent_interface_CommandWithArguments_Arguments_TWO = 1, 
    agent_interface_CommandWithArguments_Arguments_THREE = 2, 
    agent_interface_CommandWithArguments_Arguments_FOUR = 3, 
    agent_interface_CommandWithArguments_Arguments_TOTAL = 4 
} agent_interface_CommandWithArguments_Arguments;

/* Struct definitions */
typedef struct _agent_interface_Header { 
    uint32_t target_agent_id; /* Id of the receiver agent */
    uint32_t source_agent_id; /* Id of the sender agent */
    uint32_t week_number; /* week of year */
    uint32_t year; /* year */
    float timestamp; /* timestamp */
} agent_interface_Header;

typedef struct _agent_interface_CommandWithArguments { 
    agent_interface_Header header; 
    uint32_t id; /* Command Id */
    agent_interface_CommandWithArguments_Arguments number_arg_count; /* number of Arguments */
    pb_callback_t arguments; 
} agent_interface_CommandWithArguments;

typedef struct _agent_interface_Event { 
    agent_interface_Header header; 
    uint32_t id; /* Event Id */
} agent_interface_Event;


/* Helper constants for enums */
#define _agent_interface_CommandWithArguments_Arguments_MIN agent_interface_CommandWithArguments_Arguments_ONE
#define _agent_interface_CommandWithArguments_Arguments_MAX agent_interface_CommandWithArguments_Arguments_TOTAL
#define _agent_interface_CommandWithArguments_Arguments_ARRAYSIZE ((agent_interface_CommandWithArguments_Arguments)(agent_interface_CommandWithArguments_Arguments_TOTAL+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define agent_interface_Header_init_default      {0, 0, 0, 0, 0}
#define agent_interface_Event_init_default       {agent_interface_Header_init_default, 0}
#define agent_interface_CommandWithArguments_init_default {agent_interface_Header_init_default, 0, _agent_interface_CommandWithArguments_Arguments_MIN, {{NULL}, NULL}}
#define agent_interface_Header_init_zero         {0, 0, 0, 0, 0}
#define agent_interface_Event_init_zero          {agent_interface_Header_init_zero, 0}
#define agent_interface_CommandWithArguments_init_zero {agent_interface_Header_init_zero, 0, _agent_interface_CommandWithArguments_Arguments_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define agent_interface_Header_target_agent_id_tag 1
#define agent_interface_Header_source_agent_id_tag 2
#define agent_interface_Header_week_number_tag   3
#define agent_interface_Header_year_tag          4
#define agent_interface_Header_timestamp_tag     5
#define agent_interface_CommandWithArguments_header_tag 1
#define agent_interface_CommandWithArguments_id_tag 2
#define agent_interface_CommandWithArguments_number_arg_count_tag 3
#define agent_interface_CommandWithArguments_arguments_tag 4
#define agent_interface_Event_header_tag         1
#define agent_interface_Event_id_tag             2

/* Struct field encoding specification for nanopb */
#define agent_interface_Header_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FIXED32,  target_agent_id,   1) \
X(a, STATIC,   REQUIRED, FIXED32,  source_agent_id,   2) \
X(a, STATIC,   REQUIRED, FIXED32,  week_number,       3) \
X(a, STATIC,   REQUIRED, FIXED32,  year,              4) \
X(a, STATIC,   REQUIRED, FLOAT,    timestamp,         5)
#define agent_interface_Header_CALLBACK NULL
#define agent_interface_Header_DEFAULT NULL

#define agent_interface_Event_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, FIXED32,  id,                2)
#define agent_interface_Event_CALLBACK NULL
#define agent_interface_Event_DEFAULT NULL
#define agent_interface_Event_header_MSGTYPE agent_interface_Header

#define agent_interface_CommandWithArguments_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, FIXED32,  id,                2) \
X(a, STATIC,   REQUIRED, UENUM,    number_arg_count,   3) \
X(a, CALLBACK, REPEATED, STRING,   arguments,         4)
#define agent_interface_CommandWithArguments_CALLBACK pb_default_field_callback
#define agent_interface_CommandWithArguments_DEFAULT NULL
#define agent_interface_CommandWithArguments_header_MSGTYPE agent_interface_Header

extern const pb_msgdesc_t agent_interface_Header_msg;
extern const pb_msgdesc_t agent_interface_Event_msg;
extern const pb_msgdesc_t agent_interface_CommandWithArguments_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define agent_interface_Header_fields &agent_interface_Header_msg
#define agent_interface_Event_fields &agent_interface_Event_msg
#define agent_interface_CommandWithArguments_fields &agent_interface_CommandWithArguments_msg

/* Maximum encoded size of messages (where known) */
/* agent_interface_CommandWithArguments_size depends on runtime parameters */
#define agent_interface_Event_size               32
#define agent_interface_Header_size              25

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
