/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "message_interface_idl.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(agent_interface_Header, agent_interface_Header, AUTO)


PB_BIND(agent_interface_Event, agent_interface_Event, AUTO)


PB_BIND(agent_interface_CommandWithArguments, agent_interface_CommandWithArguments, AUTO)




