load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
    name = "commons",
    srcs = [""],
    hdrs = ["commons.h"],
    visibility = ["//agent_server:__pkg__",
                  "//utils/tests:__pkg__",
                  "//utils:__pkg__",
                 ]
            )