load("@rules_cc//cc:defs.bzl", "cc_library")
#load("@rules_java//java:defs.bzl", "java_library")
#load("@rules_proto//proto:defs.bzl", "proto_library")
load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

py_proto_library(
    name = "webapi_interface_py",
    srcs = ["./proto/message_interface.proto.proto"],
    visibility = ["//visibility:public"],
)
