cc_test(
    name = "communication_tests",
    srcs = ["main.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//ext_libs/googletest:main",
        "//utils:ancho_net_middleware_utils",
    ],
)
